// init.mjs - reproduce the source project's skeleton into a target directory. The
// source is this repo's own (dogfood) skeleton, so the template is real, formed
// files, not strings baked into code. The engine and auto-memory copy verbatim
// (project-agnostic). The project docs copy with the source project name
// substituted to the target name - this is where the <PROJECT> prefix is finally
// instantiated to a real name.

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

import { flag, validName } from "./args.mjs";
import { buildGitignore, PRIVACY_MODES } from "./gitignore.mjs";
import { recallMemoryPath, recallPrivacy, recallUpstream } from "./initRecall.mjs";
import { installLog } from "./installLog.mjs";
import { canonicalPath, claudeMemoryDir, fromHomeRef, SOURCE_ROOT, toHomeRef } from "./paths.mjs";

const VERBATIM_ROOT = ["CLAUDE.md"];   // no project name inside (.gitignore is generated by privacy mode)
const SUBSTITUTED_ROOT = ["AGENTS.md", "CHANGELOG.md"]; // project name in content
const STOCK_DIRS = ["WDDOCS/DESIGN", "WDDOCS/ARCHIVE", "WDDOCS/RELEASES", "WDDOCS/IDEAS", "AIDOCS/ENV", "AIDOCS/tools/staging", "TEMP"];

// Coarse, content-free recognition of what already sits at the target, so the install can
// report what it found and point at the right next step. Existence-only, never parses, so a
// malformed _index.json or a half-written data file still reads as "existing". The real
// per-file determination is the AI's job in -Setup, made safe there by migrate-archive.
function hasDataDoc(aidocsDir) {
  if (!existsSync(aidocsDir)) return false;
  try { return readdirSync(aidocsDir).some((f) => /_(MEMORY|SESSION)\.md$/.test(f)); }
  catch { return false; }
}
// True when AIDOCS holds a data doc whose project prefix is not the target name - the
// signature of a bootstrap rename (laying a new name over an existing differently-named
// project). Used to skip laying empty new-name data scaffolds before migrate-archive
// runs, so they never pollute the archive and shadow the real source at restore.
function hasForeignDataDoc(aidocsDir, name) {
  if (!existsSync(aidocsDir)) return false;
  try {
    return readdirSync(aidocsDir).some((f) => {
      const m = f.match(/^(.+)_(?:MEMORY|SESSION)\.md$/);
      return m && m[1] !== name;
    });
  } catch { return false; }
}
function recognizeTarget(target) {
  const has = (...p) => existsSync(join(target, ...p));
  if (has(".claude", "skills", "321") || has("AIDOCS", "_index.json") || hasDataDoc(join(target, "AIDOCS"))) {
    return "existing-321";
  }
  if (has("AGENTS.md") || has("CLAUDE.md") || has("README.md") || has("package.json") || has("src") || has("AIDOCS")) {
    return "generic-existing";
  }
  return "fresh";
}

// The external memory path to seed and record (absolute): an explicit override wins, else
// a reinstall's recorded path, else the derived default. Recording the resolved value (not
// re-deriving) is what insulates a project from a Claude Code key-encoding change.
function resolveMemoryPath(args, target, name) {
  const explicit = flag(args, "--memory-path") || process.env.STD321_MEMORY_PATH;
  if (explicit) return resolve(process.cwd(), explicit);
  const recalled = recallMemoryPath(target, name);
  return recalled ? fromHomeRef(recalled) : claudeMemoryDir(target);
}

// Seed Claude Code's external memory (the runtime source of truth) from the in-repo seed,
// write-if-missing per file so an existing project's external rules (custom rules, profile,
// prior canonical) are never clobbered - the reconcile pass does the authoritative refresh
// and merge. A fresh project starts empty, so this copies the full canonical set in.
function seedExternalMemory(seedDir, externalAbs) {
  if (!existsSync(seedDir)) return 0;
  mkdirSync(externalAbs, { recursive: true });
  let n = 0;
  for (const f of readdirSync(seedDir)) {
    if (f === ".gitkeep") continue;
    const dst = join(externalAbs, f);
    if (existsSync(dst)) continue;   // write-if-missing - never overwrite live external memory
    cpSync(join(seedDir, f), dst, { recursive: true });
    n++;
  }
  return n;
}

export function cmdInit(args) {
  const targetArg = args[0];
  if (!targetArg || targetArg.startsWith("--")) {
    console.error("init requires a target directory as the first argument. Usage: init <target-dir> --name <PROJECT>");
    process.exit(5);
  }
  const name = flag(args, "--name");
  if (!validName(name)) {
    console.error("init requires --name <PROJECT> (start with a letter or digit, then letters / digits / _ / - only).");
    process.exit(5);
  }
  const force = args.includes("--force");
  const target = resolve(process.cwd(), targetArg);
  if (canonicalPath(SOURCE_ROOT) === canonicalPath(target)) { console.error("init: refusing to scaffold over the source project."); process.exit(5); }
  // Privacy mode gates what the project tracks (Tier B: memory, auto-memory, WDDOCS docs).
  // Explicit --privacy wins, else recall a reinstall's mode, else default private.
  let privacy = flag(args, "--privacy");
  if (!privacy) privacy = recallPrivacy(target, name);
  if (!PRIVACY_MODES.includes(privacy)) {
    console.error(`init: --privacy must be one of ${PRIVACY_MODES.join(" / ")} (got "${privacy}").`);
    process.exit(5);
  }
  const kind = recognizeTarget(target);
  // --force rewrites scaffolds, but on an existing 321 project that desyncs the tree:
  // it rewrites the registry to the new name's data docs while the rename-skip leaves
  // the old-named docs in place (registry points at files that do not exist). It is also
  // the "force over my project" data-loss path the non-destructive migration exists to
  // avoid. Refuse it and point at setup.md. A fresh or generic target may still --force.
  if (force && kind === "existing-321") {
    console.error("init: refusing --force on an existing 321 project - it would desync the registry from the preserved data docs, and overwriting an existing project is the data-loss path the migration avoids.");
    console.error("  Migrate non-destructively: execute INSTALL/setup.md (it archives, relays, and recaptures). To start genuinely fresh, clear the AIDOCS data docs and _index.json by hand first, then init.");
    process.exit(5);
  }
  // A bootstrap rename (a new name over an existing differently-named project) must not
  // lay empty new-name data scaffolds: migrate-archive would sweep them into the archive,
  // where they would shadow the real legacy-named source at restore. The reinstall pass
  // (over the emptied post-archive tree) sees no foreign doc and lays them normally.
  const renaming = hasForeignDataDoc(join(target, "AIDOCS"), name);

  const sourceIndex = join(SOURCE_ROOT, "AIDOCS", "_index.json");
  const source = JSON.parse(readFileSync(sourceIndex, "utf8"));
  const sourceName = source.project_name;
  const sub = (s) => s.split(sourceName).join(name);

  mkdirSync(join(target, "AIDOCS"), { recursive: true });

  // 1. Project-agnostic, verbatim: the engine, the skill bodies, and the router. Skill
  // bodies reference files by domain-owned key, not by project name, so they need no
  // substitution. Auto-memory follows as the one write-if-missing exception.
  // The engine, minus machine-local runtime files: a dogfooded source may carry a
  // staging/ or state.json, which belong to the source project, not a fresh one.
  cpSync(join(SOURCE_ROOT, "AIDOCS", "tools"), join(target, "AIDOCS", "tools"), {
    recursive: true,
    filter: (src) => { const b = src.split(/[\\/]/).pop(); return b !== "state.json" && b !== "staging"; },
  });
  // Auto-memory carries project data (a filled profile, edited or custom rules), so it
  // is write-if-missing, not an unconditional overwrite: a bootstrap install over an
  // existing project must keep the project's rules intact for migrate-archive to
  // capture, since the bootstrap init runs before it. A fresh target (or --force) lays
  // the canonical set, and the post-archive reinstall sees an emptied tree and lays it
  // fresh too.
  const automemoryDst = join(target, "AIDOCS", "automemory");
  if (force || !existsSync(automemoryDst)) cpSync(join(SOURCE_ROOT, "AIDOCS", "automemory"), automemoryDst, { recursive: true });
  cpSync(join(SOURCE_ROOT, "AIDOCS", "SKILL"), join(target, "AIDOCS", "SKILL"), { recursive: true });
  const routerSrc = join(SOURCE_ROOT, ".claude", "skills", "321", "SKILL.md");
  if (existsSync(routerSrc)) {
    mkdirSync(join(target, ".claude", "skills", "321"), { recursive: true });
    cpSync(routerSrc, join(target, ".claude", "skills", "321", "SKILL.md"));
  }

  // The onboarding reference files (INSTALL/setup.md and friends): read-and-execute
  // runbooks the -Setup runner follows. Project-agnostic (they use the <PROJECT>
  // placeholder in command examples), and removed wholesale at graduation. Skip a
  // fetched engine and the INSTALL.log audit trail if either is staged in the source -
  // those are runtime, not template.
  const installSrc = join(SOURCE_ROOT, "INSTALL");
  if (existsSync(installSrc)) {
    cpSync(installSrc, join(target, "INSTALL"), {
      recursive: true,
      filter: (src) => { const b = src.split(/[\\/]/).pop(); return b !== "engine" && b !== "INSTALL.log"; },
    });
  }

  // 2-4. Scaffold-class files: the root docs (verbatim plus name-substituted), the
  // registry, and the registered data files. Write-if-missing so an install over an
  // existing project never clobbers content - the engine and runbooks above always
  // overwrite because they hold no project data, but these may. --force rewrites the
  // scaffold too. An existing data file is left for the -Setup migration to archive.
  // Resolve and record Claude Code's external memory path (auto_memory.path) - the runtime
  // source of truth. Stored home-relative so a tracked _index.json carries no absolute home
  // path. The seed below copies the canonical rules into it.
  const memAbs = resolveMemoryPath(args, target, name);
  const memRef = toHomeRef(memAbs);
  const scaffolds = [];
  for (const f of VERBATIM_ROOT) {
    const srcAbs = join(SOURCE_ROOT, f);
    if (existsSync(srcAbs)) scaffolds.push({ dst: join(target, f), body: readFileSync(srcAbs, "utf8") });
  }
  for (const f of SUBSTITUTED_ROOT) {
    scaffolds.push({ dst: join(target, f), body: sub(readFileSync(join(SOURCE_ROOT, f), "utf8")) });
  }
  // _index.json carries the resolved privacy mode, overriding the source's "full"
  // template mode. Re-serialized from the parsed source (2-space, same key order), then
  // name-substituted like the rest. .gitignore is generated by mode, not copied verbatim:
  // the source ships the "full" shape, which is wrong for both downstream modes.
  // engine.upstream resolves through three layers: an explicit --upstream / STD321_UPSTREAM
  // wins, else a recalled value (live registry or SETUP_ARCHIVE copy, so a migration's
  // reinstall preserves the original install's upstream), else the source's own value
  // (typically empty in the dogfood case, but a fork's source could carry one). When a
  // resolved upstream exists it always wins on the scaffold write - a user-customized
  // fork URL survives a reinstall because _index.json is write-if-missing, not by us
  // refusing to overwrite the scaffold value.
  const explicitUpstream = flag(args, "--upstream") || process.env.STD321_UPSTREAM || "";
  const recalledUpstream = explicitUpstream ? "" : recallUpstream(target, name);
  const upstream = explicitUpstream || recalledUpstream;
  const idxObj = { ...source, privacy, auto_memory: { ...source.auto_memory, path: memRef } };
  if (upstream) {
    idxObj.engine = { ...(idxObj.engine || {}), upstream };
  }
  scaffolds.push({ dst: join(target, "AIDOCS", "_index.json"), body: sub(`${JSON.stringify(idxObj, null, 2)}\n`) });
  scaffolds.push({ dst: join(target, ".gitignore"), body: buildGitignore(privacy) });
  // Skip the data-doc scaffolds during a bootstrap rename (see `renaming` above): an
  // empty new-name MEMORY / SESSION laid here would be archived and then shadow the real
  // source at restore. They are laid on the post-archive reinstall instead.
  if (!renaming) {
    for (const rel of Object.values(source.files)) {
      const srcAbs = join(SOURCE_ROOT, rel.replace(/^\.\//, ""));
      scaffolds.push({ dst: join(target, sub(rel).replace(/^\.\//, "")), body: sub(readFileSync(srcAbs, "utf8")) });
    }
  }
  let wrote = 0, kept = 0;
  for (const { dst, body } of scaffolds) {
    if (!force && existsSync(dst)) { kept++; continue; }
    mkdirSync(dirname(dst), { recursive: true });
    writeFileSync(dst, body, "utf8");
    wrote++;
  }
  console.log(`  scaffold: ${wrote} written, ${kept} preserved${force ? " (--force)" : ""}.`);
  installLog(target, `init: ${kind} target, scaffold ${wrote} written, ${kept} preserved${force ? " (--force)" : ""}.`);

  // 5. Stock empty dirs (kept by a .gitkeep so they survive a commit). The
  // name-based SETUP_ARCHIVE is the migration recovery-net home, preseeded so
  // migrate-archive has a place to move content into.
  for (const d of [...STOCK_DIRS, `AIDOCS/${name}_SETUP_ARCHIVE`]) {
    mkdirSync(join(target, d), { recursive: true });
    writeFileSync(join(target, d, ".gitkeep"), "", "utf8");
  }
  // public hides the auto-memory content (its rules + the user profile), so a .gitkeep
  // keeps the dir in the published skeleton. private / full track the content directly.
  if (privacy === "public") {
    mkdirSync(automemoryDst, { recursive: true });
    writeFileSync(join(automemoryDst, ".gitkeep"), "", "utf8");
  }

  // Seed Claude Code's external memory from the in-repo seed (the runtime source of truth),
  // write-if-missing so an existing project's live external rules survive for the reconcile
  // merge. The recorded auto_memory.path is where every later pass reads and writes.
  const seeded = seedExternalMemory(automemoryDst, memAbs);
  console.log(`  auto-memory: ${seeded} rule(s) seeded into ${memRef} (Claude's memory - the runtime source).`);
  installLog(target, `init: seeded ${seeded} auto-memory rule(s) into ${memRef}.`);

  console.log(`init: laid ${sourceName} skeleton into ${target} as "${name}" (privacy: ${privacy}).`);
  // Setup is part of the install, not a separate /321 -Setup the user must invoke: the
  // assistant driving the install continues into INSTALL/setup.md directly (install.md
  // step 7, install.sh step 7). Migration is non-destructive - it archives (move, not
  // delete) and parks at the reconcile gate - so the continuation is safe to auto-run.
  // The earlier "Next: /321 -Setup" wording made an AI-agent install stop and ask.
  if (kind === "fresh") {
    console.log(`  fresh project. Next: continue into setup - execute INSTALL/setup.md to fill the Big 6 from your code.`);
  } else if (kind === "existing-321") {
    console.log(`  recognized an existing 321 project. Existing content preserved. Next: execute INSTALL/setup.md now to migrate it.`);
    console.log(`  Run it through automatically - do not ask how to proceed and do not overwrite. It archives into AIDOCS/${name}_SETUP_ARCHIVE (move, never delete - the recovery net, so no git backup is needed) and parks at the reconcile gate, which is the only stop.`);
  } else {
    console.log(`  recognized an existing project (no 321 yet). Your files are untouched. Next: continue into setup - execute INSTALL/setup.md to capture it (automatic, non-destructive).`);
  }
  console.log(`  doctor: node "${join(target, "AIDOCS", "tools", "engine.mjs")}" doctor`);
}
